import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "モノがたり | 捨てられない「モノ」の使い道をみんなで考えるアプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body
        className={`font-bokutachi max-w-4xl mx-auto bg-theme text-black relative`}
      >
        <Header />
        <main className="lg:mt-24 mt-20 p-2">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
