import type { Metadata } from "next";
import "./globals.css";
import { Kiwi_Maru } from "next/font/google";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const font = Kiwi_Maru({
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

export const metadata: Metadata = {
  title:
    "モノがたり | みんなの手放せない「モノ」のこれからの活用を考えるアプリ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </head>
      <body
        className={`font-bokutachi max-w-4xl mx-auto bg-theme text-black relative`}
      >
        <Header />
        <main className="mt-20 p-2">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
